// Generated by scripts/generate-provider-catalog.mjs. Do not edit by hand.

pub const MIMO_PAYG_BASE_URL: &str = "https://api.xiaomimimo.com/v1";
pub const MIMO_PAYG_ANTHROPIC_URL: &str = "https://api.xiaomimimo.com/anthropic";
pub const MIMO_TOKEN_PLAN_DEFAULT_BASE_URL: &str = "https://token-plan-cn.xiaomimimo.com/v1";
pub const MIMO_TOKEN_PLAN_DEFAULT_ANTHROPIC_URL: &str =
    "https://token-plan-cn.xiaomimimo.com/anthropic";
pub const MIMO_TOKEN_PLAN_REGIONS: &[&str] = &["cn", "sgp", "ams"];
pub const MIMO_TOKEN_PLAN_ENDPOINTS: &[(&str, &str, &str)] = &[
    (
        "cn",
        "https://token-plan-cn.xiaomimimo.com/v1",
        "https://token-plan-cn.xiaomimimo.com/anthropic",
    ),
    (
        "sgp",
        "https://token-plan-sgp.xiaomimimo.com/v1",
        "https://token-plan-sgp.xiaomimimo.com/anthropic",
    ),
    (
        "ams",
        "https://token-plan-ams.xiaomimimo.com/v1",
        "https://token-plan-ams.xiaomimimo.com/anthropic",
    ),
];

pub const DEEPSEEK_BASE_URL: &str = "https://api.deepseek.com";
pub const DEEPSEEK_ANTHROPIC_URL: &str = "https://api.deepseek.com/anthropic";
pub const DEEPSEEK_REASONING_MODEL: &str = "deepseek-v4-pro";
pub const DEEPSEEK_SUPPORTED_MODELS_JSON: &str = "[\"deepseek-flash\",\"deepseek-v4-pro\"]";

/// Models that can be passed through natively to the provider's Responses API.
/// A provider listed here is restricted to these models; providers absent from
/// this table have no restriction.
pub const RESPONSES_NATIVE_MODELS: &[(&str, &[&str])] = &[("deepseek", &["deepseek-flash"])];

/// Custom tools (`{"type":"custom"}`) the provider's Responses API accepts.
/// A request carrying any other custom tool is rejected upstream, so it must
/// fall back to the conversion path. Providers absent from this table are
/// assumed to accept anything.
pub const RESPONSES_NATIVE_CUSTOM_TOOLS: &[(&str, &[&str])] = &[("deepseek", &["apply_patch"])];

pub const MODEL_CAPABILITIES: &[(&str, &str, &[&str])] = &[
    (
        "mimo",
        "mimo-v2.5-pro",
        &["text", "reasoning", "tools", "web_search"],
    ),
    (
        "mimo",
        "mimo-v2-pro",
        &["text", "reasoning", "tools", "web_search"],
    ),
    (
        "mimo",
        "mimo-v2.5",
        &[
            "text",
            "vision",
            "audio_in",
            "video_in",
            "reasoning",
            "tools",
            "web_search",
        ],
    ),
    (
        "mimo",
        "mimo-v2-omni",
        &["text", "vision", "audio_in", "video_in", "tools"],
    ),
    (
        "mimo",
        "mimo-v2-flash",
        &["text", "reasoning", "tools", "web_search"],
    ),
    ("mimo", "mimo-v2.5-tts", &["tts"]),
    ("mimo", "mimo-v2.5-tts-voiceclone", &["tts"]),
    ("mimo", "mimo-v2.5-tts-voicedesign", &["tts"]),
    ("mimo", "mimo-v2-tts", &["tts"]),
    (
        "deepseek",
        "deepseek-flash",
        &["text", "vision", "reasoning", "tools"],
    ),
    (
        "deepseek",
        "deepseek-v4-pro",
        &["text", "reasoning", "tools"],
    ),
    (
        "kimi",
        "kimi-k3",
        &[
            "text",
            "vision",
            "video_in",
            "reasoning",
            "tools",
            "web_search",
        ],
    ),
    (
        "kimi",
        "k3",
        &[
            "text",
            "vision",
            "video_in",
            "reasoning",
            "tools",
            "web_search",
        ],
    ),
    (
        "kimi",
        "kimi-k2.7-code",
        &[
            "text",
            "vision",
            "video_in",
            "reasoning",
            "tools",
            "web_search",
        ],
    ),
    (
        "kimi",
        "kimi-k2.7-code-highspeed",
        &[
            "text",
            "vision",
            "video_in",
            "reasoning",
            "tools",
            "web_search",
        ],
    ),
    (
        "kimi",
        "kimi-for-coding",
        &["text", "vision", "reasoning", "tools", "web_search"],
    ),
    (
        "kimi",
        "kimi-for-coding-highspeed",
        &["text", "vision", "reasoning", "tools", "web_search"],
    ),
    (
        "kimi",
        "kimi-k2.6",
        &[
            "text",
            "vision",
            "video_in",
            "reasoning",
            "tools",
            "web_search",
        ],
    ),
    (
        "kimi",
        "kimi-k2",
        &["text", "vision", "tools", "web_search"],
    ),
];

pub const MODEL_PRICING_DEFAULTS: &[(&str, &str, f64, f64)] = &[
    ("mimo", "mimo-v2.5-pro", 0.435, 0.87),
    ("mimo", "mimo-v2-pro", 1.0, 3.0),
    ("mimo", "mimo-v2.5", 0.14, 0.28),
    ("mimo", "mimo-v2-omni", 0.4, 2.0),
    ("mimo", "mimo-v2-flash", 0.1, 0.3),
    ("mimo", "mimo-v2.5-tts", 0.0, 0.0),
    ("mimo", "mimo-v2.5-tts-voiceclone", 0.0, 0.0),
    ("mimo", "mimo-v2.5-tts-voicedesign", 0.0, 0.0),
    ("mimo", "mimo-v2-tts", 0.0, 0.0),
    ("deepseek", "deepseek-flash", 0.5, 2.0),
    ("deepseek", "deepseek-v4-pro", 2.0, 8.0),
    ("anthropic", "claude-sonnet-4-6", 3.0, 15.0),
    ("anthropic", "claude-sonnet-4-7", 3.0, 15.0),
    ("anthropic", "claude-opus-4-6", 15.0, 75.0),
    ("anthropic", "claude-opus-4-7", 15.0, 75.0),
    ("anthropic", "claude-opus-4-8", 15.0, 75.0),
    ("anthropic", "claude-haiku-4-5", 0.8, 4.0),
    ("copilot", "claude-sonnet-4.6", 0.0, 0.0),
    ("copilot", "claude-sonnet-4.6-1m", 0.0, 0.0),
    ("copilot", "claude-sonnet-4.5", 0.0, 0.0),
    ("copilot", "claude-opus-4.6", 0.0, 0.0),
    ("copilot", "claude-opus-4.6-1m", 0.0, 0.0),
    ("copilot", "claude-haiku-4.5", 0.0, 0.0),
    ("openai", "gpt-4o", 2.5, 10.0),
    ("openai", "gpt-4o-mini", 0.15, 0.6),
    ("openai", "gpt-5.6", 5.0, 30.0),
    ("openai", "gpt-5.6-sol", 5.0, 30.0),
    ("openai", "gpt-5.6-terra", 2.5, 15.0),
    ("openai", "gpt-5.6-luna", 1.0, 6.0),
    ("openai", "gpt-5.5", 2.5, 10.0),
    ("openai", "gpt-5.4", 2.5, 15.0),
    ("openai", "o3", 10.0, 40.0),
    ("openai", "o4-mini", 1.1, 4.4),
    ("google_gemini", "gemini-3.5-flash", 1.5, 9.0),
    ("google_gemini", "gemini-2.5-flash", 0.15, 0.6),
    ("google_gemini", "gemini-2.5-pro", 1.25, 10.0),
    ("kimi", "kimi-k3", 3.0, 15.0),
    ("kimi", "k3", 3.0, 15.0),
    ("kimi", "kimi-k2.7-code", 0.95, 4.0),
    ("kimi", "kimi-k2.7-code-highspeed", 1.9, 8.0),
    ("kimi", "kimi-for-coding", 0.95, 4.0),
    ("kimi", "kimi-for-coding-highspeed", 1.9, 8.0),
    ("kimi", "kimi-k2.6", 0.95, 4.0),
    ("kimi", "kimi-k2", 1.0, 4.0),
    ("minimax", "MiniMax-M1", 1.0, 8.0),
    ("glm", "glm-5.2", 1.4, 4.4),
    ("glm", "glm-5", 0.55, 2.25),
    ("glm", "glm-5.1", 0.85, 3.4),
    ("glm", "glm-4-plus", 0.7, 0.7),
    ("dashscope", "qwen-max", 1.6, 6.4),
    ("xai", "grok-4.3", 1.25, 2.5),
    ("xai", "grok-3-latest", 3.0, 15.0),
    ("mistral", "mistral-large-latest", 2.0, 6.0),
    ("groq", "*", 0.0, 0.0),
    ("cerebras", "*", 0.0, 0.0),
];

pub const MODEL_CONTEXT_WINDOW: &[(&str, &str, u32)] = &[
    ("mimo", "mimo-v2.5-pro", 128000),
    ("mimo", "mimo-v2-pro", 128000),
    ("mimo", "mimo-v2.5", 128000),
    ("mimo", "mimo-v2-omni", 128000),
    ("mimo", "mimo-v2-flash", 128000),
    ("deepseek", "deepseek-flash", 128000),
    ("deepseek", "deepseek-v4-pro", 128000),
    ("kimi", "kimi-k3", 1048576),
    ("kimi", "k3", 1048576),
    ("kimi", "kimi-k2.7-code", 262144),
    ("kimi", "kimi-k2.7-code-highspeed", 262144),
    ("kimi", "kimi-for-coding", 262144),
    ("kimi", "kimi-for-coding-highspeed", 262144),
    ("kimi", "kimi-k2.6", 262144),
    ("kimi", "kimi-k2", 131072),
];

pub const DEPRECATED_MODELS: &[(&str, &str)] = &[
    ("deepseek", "deepseek-chat"),
    ("deepseek", "deepseek-reasoner"),
    ("deepseek", "deepseek-v4-flash"),
    ("deepseek", "deepseek-v4-flash-vision-exp"),
    ("kimi", "kimi-k2"),
];

pub const RECOMMENDED_MAPPING_PROFILES: &[(&str, &str, &str, &str, &str, bool)] = &[
    ("mimo", "default", "default", "reasoning", "default", true),
    (
        "deepseek",
        "reasoning",
        "default",
        "reasoning",
        "default",
        true,
    ),
    ("kimi", "reasoning", "default", "reasoning", "default", true),
];
