//! AppError 错误码常量——集中所有面向前端的 error code 字符串。
//!
//! ## 为什么这样写
//!
//! `AppError::new("CODE_STR", message)` 散落在 219 处调用点，拼写错误（如
//! "PROVDER_API_KEY_MISSING"）只能靠 code review 发现，编译器和测试都看不到。
//! 改成 `AppError::new(codes::PROVIDER_API_KEY_MISSING, message)` 后，拼错就是
//! `unknown identifier` 编译错误。
//!
//! ## 契约约束
//!
//! 这些 code **字符串值是面向前端的契约**（前端有 `err.code === "NO_API_KEY"`
//! 这类判断），所以 const 的字面值必须和原本散落的字符串完全一致——只是把字符串
//! 重复挪到一个地方，不改语义。新增 code 必须先在前端处理逻辑里达成共识再加。
//!
//! ## 不在这里的
//!
//! - `NOT_FOUND` / `VALIDATION_ERROR` / `DATABASE_ERROR` / `NETWORK_ERROR` /
//!   `INTERNAL_ERROR`：由 AppError 的便捷构造方法 (`not_found`, `validation`,
//!   `database`, `internal`, `From<reqwest::Error>`) 内部产出，不通过 `new`。
//! - 测试 sentinel 如 `"TEST"` / `"TEST_CODE"` / `"CODE"` / `"UNKNOWN_CODE"`：
//!   仅为单测虚构，不属于面向前端契约，保留字符串。

pub const ACTIVE_PROVIDER_NOT_FOUND: &str = "ACTIVE_PROVIDER_NOT_FOUND";
pub const ATOMCODE_CONFIG_NOT_FOUND: &str = "ATOMCODE_CONFIG_NOT_FOUND";
pub const ATOMCODE_CONFIG_OPEN_FAILED: &str = "ATOMCODE_CONFIG_OPEN_FAILED";
pub const ATOMCODE_CONFIG_WRITE_FAILED: &str = "ATOMCODE_CONFIG_WRITE_FAILED";
pub const ATOMCODE_NO_SAVED_FILES: &str = "ATOMCODE_NO_SAVED_FILES";
pub const ATOMCODE_RESTORE_FAILED: &str = "ATOMCODE_RESTORE_FAILED";
pub const ATOMCODE_SAVE_FAILED: &str = "ATOMCODE_SAVE_FAILED";
pub const BROTLI_DECODE_FAILED: &str = "BROTLI_DECODE_FAILED";
pub const CHAT_PARSE_ERROR: &str = "CHAT_PARSE_ERROR";
pub const CLAUDE_CONFIG_NOT_FOUND: &str = "CLAUDE_CONFIG_NOT_FOUND";
pub const CLAUDE_CONFIG_OPEN_FAILED: &str = "CLAUDE_CONFIG_OPEN_FAILED";
pub const CLAUDE_CONFIG_PARSE_ERROR: &str = "CLAUDE_CONFIG_PARSE_ERROR";
pub const CLAUDE_CONFIG_WRITE_FAILED: &str = "CLAUDE_CONFIG_WRITE_FAILED";
pub const CLAUDE_DESKTOP_META_INVALID: &str = "CLAUDE_DESKTOP_META_INVALID";
pub const CLAUDE_DESKTOP_NO_3P: &str = "CLAUDE_DESKTOP_NO_3P";
pub const CLAUDE_DESKTOP_PATH_INVALID: &str = "CLAUDE_DESKTOP_PATH_INVALID";
pub const CLAUDE_DESKTOP_UNSUPPORTED_OS: &str = "CLAUDE_DESKTOP_UNSUPPORTED_OS";
pub const CLAUDE_DESKTOP_WRITE_FAILED: &str = "CLAUDE_DESKTOP_WRITE_FAILED";
pub const CLAUDE_NO_SAVED_FILES: &str = "CLAUDE_NO_SAVED_FILES";
pub const CLAUDE_RESTORE_FAILED: &str = "CLAUDE_RESTORE_FAILED";
pub const CLAUDE_SAVE_FAILED: &str = "CLAUDE_SAVE_FAILED";
/// 网关内部日志标记:流式响应中途客户端断开(只写 request_logs,不返回给前端调用)。
pub const CLIENT_DISCONNECTED: &str = "CLIENT_DISCONNECTED";
pub const CLIENT_PROCESS_KILL_DENIED: &str = "CLIENT_PROCESS_KILL_DENIED";
pub const CLIENT_PROCESS_KILL_FAILED: &str = "CLIENT_PROCESS_KILL_FAILED";
pub const CLIENT_PROCESS_NOT_FOUND: &str = "CLIENT_PROCESS_NOT_FOUND";
pub const CLIENT_RESTORE_FAILED: &str = "CLIENT_RESTORE_FAILED";
pub const CODEX_CONFIG_NOT_FOUND: &str = "CODEX_CONFIG_NOT_FOUND";
pub const CODEX_CONFIG_OPEN_FAILED: &str = "CODEX_CONFIG_OPEN_FAILED";
pub const CODEX_CONFIG_WRITE_FAILED: &str = "CODEX_CONFIG_WRITE_FAILED";
pub const CODEX_NO_SAVED_FILES: &str = "CODEX_NO_SAVED_FILES";
pub const CODEX_RESTORE_FAILED: &str = "CODEX_RESTORE_FAILED";
pub const CODEX_SAVE_FAILED: &str = "CODEX_SAVE_FAILED";
pub const CONFIG_IMPORT_PARSE_ERROR: &str = "CONFIG_IMPORT_PARSE_ERROR";
pub const CONFIG_IMPORT_VERSION_MISMATCH: &str = "CONFIG_IMPORT_VERSION_MISMATCH";
pub const COUNT_TOKENS_PARSE_ERROR: &str = "COUNT_TOKENS_PARSE_ERROR";
pub const DEFLATE_DECODE_FAILED: &str = "DEFLATE_DECODE_FAILED";
pub const DSH_CONFIG_NOT_FOUND: &str = "DSH_CONFIG_NOT_FOUND";
pub const DSH_CONFIG_OPEN_FAILED: &str = "DSH_CONFIG_OPEN_FAILED";
pub const DSH_CONFIG_PARSE_ERROR: &str = "DSH_CONFIG_PARSE_ERROR";
pub const DSH_CONFIG_WRITE_FAILED: &str = "DSH_CONFIG_WRITE_FAILED";
pub const GROK_CONFIG_NOT_FOUND: &str = "GROK_CONFIG_NOT_FOUND";
pub const GROK_CONFIG_OPEN_FAILED: &str = "GROK_CONFIG_OPEN_FAILED";
pub const GROK_CONFIG_WRITE_FAILED: &str = "GROK_CONFIG_WRITE_FAILED";
pub const KIMI_CONFIG_NOT_FOUND: &str = "KIMI_CONFIG_NOT_FOUND";
pub const KIMI_CONFIG_OPEN_FAILED: &str = "KIMI_CONFIG_OPEN_FAILED";
pub const KIMI_CONFIG_WRITE_FAILED: &str = "KIMI_CONFIG_WRITE_FAILED";
pub const DIAGNOSTIC_EXPORT_FAILED: &str = "DIAGNOSTIC_EXPORT_FAILED";
pub const DAILY_BUDGET_EXCEEDED: &str = "DAILY_BUDGET_EXCEEDED";
pub const FAILOVER_EXHAUSTED: &str = "FAILOVER_EXHAUSTED";
pub const FUNCTION_CALL_OUTPUT_ID_MISSING: &str = "FUNCTION_CALL_OUTPUT_ID_MISSING";
pub const GATEWAY_ALREADY_RUNNING: &str = "GATEWAY_ALREADY_RUNNING";
pub const GATEWAY_AUTH_INVALID: &str = "GATEWAY_AUTH_INVALID";
pub const GATEWAY_AUTH_MISSING: &str = "GATEWAY_AUTH_MISSING";
pub const GATEWAY_BIND_ERROR: &str = "GATEWAY_BIND_ERROR";
pub const GATEWAY_HOST_REJECTED: &str = "GATEWAY_HOST_REJECTED";
pub const GATEWAY_NOT_RUNNING: &str = "GATEWAY_NOT_RUNNING";
pub const GATEWAY_ORIGIN_REJECTED: &str = "GATEWAY_ORIGIN_REJECTED";
pub const GATEWAY_PORT_IN_USE: &str = "GATEWAY_PORT_IN_USE";
pub const GATEWAY_TLS_LOAD_FAILED: &str = "GATEWAY_TLS_LOAD_FAILED";
pub const GEMINI_CONFIG_NOT_FOUND: &str = "GEMINI_CONFIG_NOT_FOUND";
pub const GEMINI_CONFIG_OPEN_FAILED: &str = "GEMINI_CONFIG_OPEN_FAILED";
pub const GEMINI_CONFIG_PARSE_ERROR: &str = "GEMINI_CONFIG_PARSE_ERROR";
pub const GEMINI_CONFIG_WRITE_FAILED: &str = "GEMINI_CONFIG_WRITE_FAILED";
pub const GEMINI_NO_SAVED_FILES: &str = "GEMINI_NO_SAVED_FILES";
pub const GEMINI_PARSE_ERROR: &str = "GEMINI_PARSE_ERROR";
pub const GEMINI_RESTORE_FAILED: &str = "GEMINI_RESTORE_FAILED";
pub const GEMINI_SAVE_FAILED: &str = "GEMINI_SAVE_FAILED";
pub const GZIP_DECODE_FAILED: &str = "GZIP_DECODE_FAILED";
pub const INSTRUCTIONS_BAD_MODE: &str = "INSTRUCTIONS_BAD_MODE";
pub const INSTRUCTIONS_BAD_SCOPE: &str = "INSTRUCTIONS_BAD_SCOPE";
pub const INSTRUCTIONS_IMPORT_BAD_JSON: &str = "INSTRUCTIONS_IMPORT_BAD_JSON";
pub const INSTRUCTIONS_TEMPLATE_NOT_FOUND: &str = "INSTRUCTIONS_TEMPLATE_NOT_FOUND";
pub const INSTRUCTIONS_WRITE_FAILED: &str = "INSTRUCTIONS_WRITE_FAILED";
pub const INVALID_REQUEST_BODY: &str = "INVALID_REQUEST_BODY";
pub const LOCAL_ACCESS_TOKEN_GENERATE_FAILED: &str = "LOCAL_ACCESS_TOKEN_GENERATE_FAILED";
pub const LOCAL_ACCESS_TOKEN_NOT_FOUND: &str = "LOCAL_ACCESS_TOKEN_NOT_FOUND";
pub const LOCAL_ACCESS_TOKEN_REGENERATE_FAILED: &str = "LOCAL_ACCESS_TOKEN_REGENERATE_FAILED";
pub const MCP_CONFIG_PARSE_ERROR: &str = "MCP_CONFIG_PARSE_ERROR";
pub const MCP_CONFIG_WRITE_FAILED: &str = "MCP_CONFIG_WRITE_FAILED";
pub const MESSAGES_PARSE_ERROR: &str = "MESSAGES_PARSE_ERROR";
pub const NO_PROVIDER_CANDIDATE: &str = "NO_PROVIDER_CANDIDATE";
pub const OPENCODE_CONFIG_NOT_FOUND: &str = "OPENCODE_CONFIG_NOT_FOUND";
pub const OPENCODE_CONFIG_OPEN_FAILED: &str = "OPENCODE_CONFIG_OPEN_FAILED";
pub const OPENCODE_CONFIG_PARSE_ERROR: &str = "OPENCODE_CONFIG_PARSE_ERROR";
pub const OPENCODE_CONFIG_WRITE_FAILED: &str = "OPENCODE_CONFIG_WRITE_FAILED";
pub const PASS_THROUGH_REQUEST_FAILED: &str = "PASS_THROUGH_REQUEST_FAILED";
pub const PASS_THROUGH_STREAM_FAILED: &str = "PASS_THROUGH_STREAM_FAILED";
pub const PROTOCOL_TRANSFORM_NOT_SUPPORTED: &str = "PROTOCOL_TRANSFORM_NOT_SUPPORTED";
pub const PROVIDER_API_KEY_MISSING: &str = "PROVIDER_API_KEY_MISSING";
pub const PROVIDER_REQUEST_FAILED: &str = "PROVIDER_REQUEST_FAILED";
pub const REQUEST_BODY_TOO_LARGE: &str = "REQUEST_BODY_TOO_LARGE";
pub const RESPONSES_PARSE_ERROR: &str = "RESPONSES_PARSE_ERROR";
pub const ROUTE_NOT_SUPPORTED: &str = "ROUTE_NOT_SUPPORTED";
pub const ROUTE_PROFILE_DELETE_DEFAULT_FORBIDDEN: &str = "ROUTE_PROFILE_DELETE_DEFAULT_FORBIDDEN";
pub const ROUTE_PROFILE_EMPTY: &str = "ROUTE_PROFILE_EMPTY";
pub const ROUTE_PROFILE_NOT_FOUND: &str = "ROUTE_PROFILE_NOT_FOUND";
pub const ROUTE_PROVIDER_DUPLICATED: &str = "ROUTE_PROVIDER_DUPLICATED";
pub const ROUTE_TEMPLATE_INVALID: &str = "ROUTE_TEMPLATE_INVALID";
pub const ROUTE_TEMPLATE_NOTHING_TO_ROLLBACK: &str = "ROUTE_TEMPLATE_NOTHING_TO_ROLLBACK";
pub const SESSION_DELETE_FAILED: &str = "SESSION_DELETE_FAILED";
pub const SESSION_NOT_FOUND: &str = "SESSION_NOT_FOUND";
pub const SESSION_READ_FAILED: &str = "SESSION_READ_FAILED";
pub const SKILL_BAD_ID: &str = "SKILL_BAD_ID";
pub const SKILL_BAD_SOURCE: &str = "SKILL_BAD_SOURCE";
pub const SKILL_DELETE_FAILED: &str = "SKILL_DELETE_FAILED";
pub const SKILL_EXISTS: &str = "SKILL_EXISTS";
pub const SKILL_IMPORT_BAD_JSON: &str = "SKILL_IMPORT_BAD_JSON";
pub const SKILL_NOT_FOUND: &str = "SKILL_NOT_FOUND";
pub const SKILL_NO_MANIFEST: &str = "SKILL_NO_MANIFEST";
pub const SKILL_TOGGLE_FAILED: &str = "SKILL_TOGGLE_FAILED";
pub const SKILL_WRITE_FAILED: &str = "SKILL_WRITE_FAILED";
pub const SKILL_ZIP_INVALID: &str = "SKILL_ZIP_INVALID";
pub const SKILL_ZIP_NO_MANIFEST: &str = "SKILL_ZIP_NO_MANIFEST";
pub const SKILL_ZIP_NO_NAME: &str = "SKILL_ZIP_NO_NAME";
pub const SKILL_ZIP_UNSAFE: &str = "SKILL_ZIP_UNSAFE";
pub const TRANSFORM_ERROR: &str = "TRANSFORM_ERROR";
pub const UNSUPPORTED_CONTENT_ENCODING: &str = "UNSUPPORTED_CONTENT_ENCODING";
pub const UPSTREAM_NON_STREAM_ERROR: &str = "UPSTREAM_NON_STREAM_ERROR";
pub const UPSTREAM_STREAM_ERROR: &str = "UPSTREAM_STREAM_ERROR";
pub const ZSTD_DECODE_FAILED: &str = "ZSTD_DECODE_FAILED";
