#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

run() {
  echo
  echo "==> $*"
  "$@"
}

# 顺序按"快且常踩 → 慢"排,快速失败。format:check 与 cargo cli test 是
# 之前漏掉、导致 CI 连红的两项,务必保留。
run bash scripts/check-version-consistency.sh
run pnpm format:check
run pnpm lint
run pnpm build
run cargo fmt --manifest-path src-tauri/Cargo.toml --check
run cargo clippy --manifest-path src-tauri/Cargo.toml --no-default-features --features cli --lib -- -D warnings
run cargo test --manifest-path src-tauri/Cargo.toml --no-default-features --features cli --lib
# 与 CI fixture-tests job 对齐:默认 desktop feature 再跑 clippy + lib test,
# desktop lib test 会重新生成 src/lib/bindings.ts,随后检查是否有未提交的漂移。
run cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets -- -D warnings
run cargo test --manifest-path src-tauri/Cargo.toml --lib
if ! git diff --exit-code -- src/lib/bindings.ts; then
  echo "src/lib/bindings.ts is stale: commit the file regenerated by the desktop lib test." >&2
  exit 1
fi
run node scripts/test-playwright-smoke.mjs
run pnpm vitest run
run pnpm docs:download:check
run pnpm test:quickstart
