// Generated by scripts/generate-provider-catalog.mjs. Do not edit by hand.

export const GENERATED_PROVIDER_CATALOG = {
  mimo: {
    schemaVersion: 1,
    order: 10,
    type: "mimo",
    displayName: "Xiaomi MiMo",
    displayNameZh: "小米 MiMo",
    aliases: ["mimo", "xiaomi"],
    protocols: ["openai_chat_completions", "anthropic_messages"],
    endpoints: {
      payg: {
        baseUrl: "https://api.xiaomimimo.com/v1",
        anthropicBaseUrl: "https://api.xiaomimimo.com/anthropic",
      },
      tokenPlanRegions: {
        cn: {
          baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
          anthropicBaseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
        },
        sgp: {
          baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
          anthropicBaseUrl: "https://token-plan-sgp.xiaomimimo.com/anthropic",
        },
        ams: {
          baseUrl: "https://token-plan-ams.xiaomimimo.com/v1",
          anthropicBaseUrl: "https://token-plan-ams.xiaomimimo.com/anthropic",
        },
      },
    },
    defaultModel: "mimo-v2.5-pro",
    reasoningModel: "mimo-v2.5-pro",
    recommendedMapping: {
      codexPrimaryTarget: "default",
      codexMiniTarget: "default",
      claudePrimaryTarget: "reasoning",
      claudeSmallTarget: "default",
      repairLegacy1m: true,
    },
    supportedModels: [
      "mimo-v2.5-pro",
      "mimo-v2-pro",
      "mimo-v2.5",
      "mimo-v2-omni",
      "mimo-v2-flash",
    ],
    models: [
      {
        id: "mimo-v2.5-pro",
        capabilities: ["text", "reasoning", "tools", "web_search"],
        pricing: {
          inputPerMillion: 0.435,
          outputPerMillion: 0.87,
        },
        contextWindow: 128000,
      },
      {
        id: "mimo-v2-pro",
        capabilities: ["text", "reasoning", "tools", "web_search"],
        pricing: {
          inputPerMillion: 1,
          outputPerMillion: 3,
        },
        contextWindow: 128000,
      },
      {
        id: "mimo-v2.5",
        capabilities: [
          "text",
          "vision",
          "audio_in",
          "video_in",
          "reasoning",
          "tools",
          "web_search",
        ],
        pricing: {
          inputPerMillion: 0.14,
          outputPerMillion: 0.28,
        },
        contextWindow: 128000,
      },
      {
        id: "mimo-v2-omni",
        capabilities: ["text", "vision", "audio_in", "video_in", "tools"],
        pricing: {
          inputPerMillion: 0.4,
          outputPerMillion: 2,
        },
        contextWindow: 128000,
      },
      {
        id: "mimo-v2-flash",
        capabilities: ["text", "reasoning", "tools", "web_search"],
        pricing: {
          inputPerMillion: 0.1,
          outputPerMillion: 0.3,
        },
        contextWindow: 128000,
      },
      {
        id: "mimo-v2.5-tts",
        capabilities: ["tts"],
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "mimo-v2.5-tts-voiceclone",
        capabilities: ["tts"],
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "mimo-v2.5-tts-voicedesign",
        capabilities: ["tts"],
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "mimo-v2-tts",
        capabilities: ["tts"],
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
    ],
    docs: {
      handlingEn:
        "Multi-turn `reasoning_content` round-trip, region-aware `tp-*` host auto-routing, temperature strip in thinking mode, tool_choice non-auto strip, omni web_search strip, web_search builtin gated by matrix, Web Search Plugin auto-degrade / retry",
      handlingZh:
        "多轮 `reasoning_content` 回环、`tp-*` host 按区域自动切换、思考态剥 temperature、tool_choice 非 auto 剥除、omni web_search 剥除、web_search builtin 按矩阵翻译、Web Search Plugin 自动降级 / 重试",
    },
    sync: {
      envVar: "MIMO_API_KEY",
      modelsUrl: "https://api.xiaomimimo.com/v1/models",
      authHeader: "bearer",
      excludeRegex: ["tts"],
    },
  },
  deepseek: {
    schemaVersion: 1,
    order: 20,
    type: "deepseek",
    displayName: "DeepSeek",
    displayNameZh: "DeepSeek",
    aliases: ["deepseek"],
    protocols: ["openai_chat_completions", "anthropic_messages"],
    endpoints: {
      baseUrl: "https://api.deepseek.com",
      anthropicBaseUrl: "https://api.deepseek.com/anthropic",
    },
    responsesModels: ["deepseek-flash"],
    responsesCustomTools: ["apply_patch"],
    defaultModel: "deepseek-flash",
    reasoningModel: "deepseek-v4-pro",
    recommendedMapping: {
      codexPrimaryTarget: "reasoning",
      codexMiniTarget: "default",
      claudePrimaryTarget: "reasoning",
      claudeSmallTarget: "default",
      repairLegacy1m: true,
    },
    supportedModels: ["deepseek-flash", "deepseek-v4-pro"],
    deprecatedModels: [
      "deepseek-chat",
      "deepseek-reasoner",
      "deepseek-v4-flash",
      "deepseek-v4-flash-vision-exp",
    ],
    models: [
      {
        id: "deepseek-flash",
        capabilities: ["text", "vision", "reasoning", "tools"],
        pricing: {
          inputPerMillion: 0.5,
          outputPerMillion: 2,
        },
        contextWindow: 128000,
      },
      {
        id: "deepseek-v4-pro",
        capabilities: ["text", "reasoning", "tools"],
        pricing: {
          inputPerMillion: 2,
          outputPerMillion: 8,
        },
        contextWindow: 128000,
      },
    ],
    docs: {
      handlingEn:
        "deepseek-flash preserves image inputs; deepseek-v4-pro strips images with an explicit notice; DeepSeek V4 thinking history reasoning backfill, schema cleaning, message reordering",
      handlingZh:
        "deepseek-flash 保留图片输入；deepseek-v4-pro 剥离图片并注入可解释提示；DeepSeek V4 thinking 历史 reasoning 回填、schema 清洗、消息重排",
    },
    sync: {
      envVar: "DEEPSEEK_API_KEY",
      modelsUrl: "https://api.deepseek.com/models",
      authHeader: "bearer",
    },
  },
  anthropic: {
    schemaVersion: 1,
    order: 30,
    type: "anthropic",
    displayName: "Anthropic (Claude)",
    displayNameZh: "Anthropic（Claude）",
    aliases: ["anthropic", "claude"],
    protocols: ["anthropic_messages"],
    endpoints: {
      baseUrl: "https://api.anthropic.com",
    },
    defaultModel: "claude-opus-4-8",
    supportedModels: [
      "claude-sonnet-4-7",
      "claude-opus-4-8",
      "claude-haiku-4-5",
    ],
    models: [
      {
        id: "claude-sonnet-4-6",
        pricing: {
          inputPerMillion: 3,
          outputPerMillion: 15,
        },
      },
      {
        id: "claude-sonnet-4-7",
        pricing: {
          inputPerMillion: 3,
          outputPerMillion: 15,
        },
      },
      {
        id: "claude-opus-4-6",
        pricing: {
          inputPerMillion: 15,
          outputPerMillion: 75,
        },
      },
      {
        id: "claude-opus-4-7",
        pricing: {
          inputPerMillion: 15,
          outputPerMillion: 75,
        },
      },
      {
        id: "claude-opus-4-8",
        pricing: {
          inputPerMillion: 15,
          outputPerMillion: 75,
        },
      },
      {
        id: "claude-haiku-4-5",
        pricing: {
          inputPerMillion: 0.8,
          outputPerMillion: 4,
        },
      },
    ],
    docs: {
      handlingEn:
        "`tool_use`/`tool_result`, `input_schema`, thinking budget, native cache_control",
      handlingZh:
        "`tool_use`/`tool_result`、`input_schema`、thinking budget、原生 cache_control",
    },
    sync: {
      envVar: "ANTHROPIC_API_KEY",
      modelsUrl: "https://api.anthropic.com/v1/models",
      authHeader: "x-api-key",
      headers: {
        "anthropic-version": "2023-06-01",
      },
    },
  },
  copilot: {
    schemaVersion: 1,
    order: 35,
    type: "copilot",
    displayName: "GitHub Copilot",
    displayNameZh: "GitHub Copilot",
    aliases: ["copilot", "github_copilot"],
    protocols: ["anthropic_messages", "openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.githubcopilot.com",
      anthropicBaseUrl: "https://api.githubcopilot.com",
    },
    defaultModel: "claude-sonnet-4.6",
    supportedModels: [
      "claude-sonnet-4.6",
      "claude-sonnet-4.6-1m",
      "claude-sonnet-4.5",
      "claude-opus-4.6",
      "claude-opus-4.6-1m",
      "claude-haiku-4.5",
    ],
    models: [
      {
        id: "claude-sonnet-4.6",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "claude-sonnet-4.6-1m",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "claude-sonnet-4.5",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "claude-opus-4.6",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "claude-opus-4.6-1m",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
      {
        id: "claude-haiku-4.5",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
    ],
    docs: {
      handlingEn:
        "GitHub token → Copilot bearer exchange, `x-initiator` billing classification, Claude model dash→dot normalization",
      handlingZh:
        "GitHub token → Copilot bearer 交换、`x-initiator` 计费分类、Claude 模型 dash→dot 归一化",
    },
  },
  openai: {
    schemaVersion: 1,
    order: 40,
    type: "openai",
    displayName: "OpenAI",
    displayNameZh: "OpenAI",
    aliases: ["openai"],
    protocols: ["openai_chat_completions", "openai_responses"],
    endpoints: {
      baseUrl: "https://api.openai.com",
      responsesBaseUrl: "https://api.openai.com",
    },
    defaultModel: "gpt-5.6-terra",
    supportedModels: [
      "gpt-4o",
      "gpt-4o-mini",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
      "gpt-5.5",
      "o3",
      "o4-mini",
    ],
    models: [
      {
        id: "gpt-4o",
        pricing: {
          inputPerMillion: 2.5,
          outputPerMillion: 10,
        },
      },
      {
        id: "gpt-4o-mini",
        pricing: {
          inputPerMillion: 0.15,
          outputPerMillion: 0.6,
        },
      },
      {
        id: "gpt-5.6",
        pricing: {
          inputPerMillion: 5,
          outputPerMillion: 30,
        },
      },
      {
        id: "gpt-5.6-sol",
        pricing: {
          inputPerMillion: 5,
          outputPerMillion: 30,
        },
      },
      {
        id: "gpt-5.6-terra",
        pricing: {
          inputPerMillion: 2.5,
          outputPerMillion: 15,
        },
      },
      {
        id: "gpt-5.6-luna",
        pricing: {
          inputPerMillion: 1,
          outputPerMillion: 6,
        },
      },
      {
        id: "gpt-5.5",
        pricing: {
          inputPerMillion: 2.5,
          outputPerMillion: 10,
        },
      },
      {
        id: "gpt-5.4",
        pricing: {
          inputPerMillion: 2.5,
          outputPerMillion: 15,
        },
      },
      {
        id: "o3",
        pricing: {
          inputPerMillion: 10,
          outputPerMillion: 40,
        },
      },
      {
        id: "o4-mini",
        pricing: {
          inputPerMillion: 1.1,
          outputPerMillion: 4.4,
        },
      },
    ],
    docs: {
      handlingEn: "None (Responses passthrough or Chat conversion)",
      handlingZh: "无（Responses 透传或 Chat 转换）",
    },
    sync: {
      envVar: "OPENAI_API_KEY",
      modelsUrl: "https://api.openai.com/v1/models",
      authHeader: "bearer",
    },
  },
  google_gemini: {
    schemaVersion: 1,
    order: 50,
    type: "google_gemini",
    displayName: "Google Gemini",
    displayNameZh: "Google Gemini",
    aliases: ["google_gemini", "gemini"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl:
        "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    },
    defaultModel: "gemini-3.5-flash",
    supportedModels: ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-2.5-pro"],
    models: [
      {
        id: "gemini-3.5-flash",
        pricing: {
          inputPerMillion: 1.5,
          outputPerMillion: 9,
        },
      },
      {
        id: "gemini-2.5-flash",
        pricing: {
          inputPerMillion: 0.15,
          outputPerMillion: 0.6,
        },
      },
      {
        id: "gemini-2.5-pro",
        pricing: {
          inputPerMillion: 1.25,
          outputPerMillion: 10,
        },
      },
    ],
    docs: {
      handlingEn: "None",
      handlingZh: "无",
    },
    sync: {
      envVar: "GEMINI_API_KEY",
      modelsUrl: "https://generativelanguage.googleapis.com/v1beta/models",
      authHeader: "query:key",
      idPrefixToStrip: "models/",
    },
  },
  kimi: {
    schemaVersion: 1,
    order: 60,
    type: "kimi",
    displayName: "Kimi / Moonshot",
    displayNameZh: "Kimi / Moonshot",
    aliases: ["kimi", "moonshot"],
    protocols: ["openai_chat_completions", "anthropic_messages"],
    endpoints: {
      baseUrl: "https://api.moonshot.cn",
      anthropicBaseUrl: "https://api.moonshot.cn/anthropic",
    },
    defaultModel: "kimi-k3",
    reasoningModel: "kimi-k3",
    recommendedMapping: {
      codexPrimaryTarget: "reasoning",
      codexMiniTarget: "default",
      claudePrimaryTarget: "reasoning",
      claudeSmallTarget: "default",
      repairLegacy1m: true,
    },
    supportedModels: [
      "kimi-k3",
      "k3",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-for-coding",
      "kimi-for-coding-highspeed",
      "kimi-k2.6",
      "kimi-k2",
    ],
    deprecatedModels: ["kimi-k2"],
    models: [
      {
        id: "kimi-k3",
        capabilities: [
          "text",
          "vision",
          "video_in",
          "reasoning",
          "tools",
          "web_search",
        ],
        pricing: {
          inputPerMillion: 3,
          outputPerMillion: 15,
        },
        contextWindow: 1048576,
      },
      {
        id: "k3",
        capabilities: [
          "text",
          "vision",
          "video_in",
          "reasoning",
          "tools",
          "web_search",
        ],
        pricing: {
          inputPerMillion: 3,
          outputPerMillion: 15,
        },
        contextWindow: 1048576,
      },
      {
        id: "kimi-k2.7-code",
        capabilities: [
          "text",
          "vision",
          "video_in",
          "reasoning",
          "tools",
          "web_search",
        ],
        pricing: {
          inputPerMillion: 0.95,
          outputPerMillion: 4,
        },
        contextWindow: 262144,
      },
      {
        id: "kimi-k2.7-code-highspeed",
        capabilities: [
          "text",
          "vision",
          "video_in",
          "reasoning",
          "tools",
          "web_search",
        ],
        pricing: {
          inputPerMillion: 1.9,
          outputPerMillion: 8,
        },
        contextWindow: 262144,
      },
      {
        id: "kimi-for-coding",
        capabilities: ["text", "vision", "reasoning", "tools", "web_search"],
        pricing: {
          inputPerMillion: 0.95,
          outputPerMillion: 4,
        },
        contextWindow: 262144,
      },
      {
        id: "kimi-for-coding-highspeed",
        capabilities: ["text", "vision", "reasoning", "tools", "web_search"],
        pricing: {
          inputPerMillion: 1.9,
          outputPerMillion: 8,
        },
        contextWindow: 262144,
      },
      {
        id: "kimi-k2.6",
        capabilities: [
          "text",
          "vision",
          "video_in",
          "reasoning",
          "tools",
          "web_search",
        ],
        pricing: {
          inputPerMillion: 0.95,
          outputPerMillion: 4,
        },
        contextWindow: 262144,
      },
      {
        id: "kimi-k2",
        capabilities: ["text", "vision", "tools", "web_search"],
        pricing: {
          inputPerMillion: 1,
          outputPerMillion: 4,
        },
        contextWindow: 131072,
      },
    ],
    extraHeaders: '{"User-Agent":"KimiCLI/1.40.0"}',
    docs: {
      handlingEn:
        "`web_search` → `builtin_function`/`$web_search`; K3 uses `reasoning_effort:max` (no K2 `thinking` param); coding models keep thinking on/off control",
      handlingZh:
        "`web_search` → `builtin_function`/`$web_search`；K3 使用 `reasoning_effort:max`（不用 K2 的 `thinking` 参数）；Coding 模型保留 thinking 开关控制",
    },
    sync: {
      envVar: "MOONSHOT_API_KEY",
      modelsUrl: "https://api.moonshot.cn/v1/models",
      authHeader: "bearer",
    },
  },
  minimax: {
    schemaVersion: 1,
    order: 70,
    type: "minimax",
    displayName: "MiniMax",
    displayNameZh: "MiniMax",
    aliases: ["minimax"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.minimax.chat",
    },
    defaultModel: "MiniMax-M1",
    supportedModels: ["MiniMax-M1"],
    models: [
      {
        id: "MiniMax-M1",
        pricing: {
          inputPerMillion: 1,
          outputPerMillion: 8,
        },
      },
    ],
    docs: {
      handlingEn:
        "Strip reasoning_effort / response_format, `<think>` extraction",
      handlingZh: "去 reasoning_effort / response_format、`<think>` 提取",
    },
    sync: {
      envVar: "MINIMAX_API_KEY",
      modelsUrl: "https://api.minimax.chat/v1/models",
      authHeader: "bearer",
    },
  },
  glm: {
    schemaVersion: 1,
    order: 80,
    type: "glm",
    displayName: "GLM (Zhipu)",
    displayNameZh: "智谱 GLM",
    aliases: ["glm", "zhipu"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
      anthropicBaseUrl: "https://open.bigmodel.cn/api/anthropic",
    },
    defaultModel: "glm-5.2",
    supportedModels: ["glm-5.2", "glm-5", "glm-5.1", "glm-4-plus"],
    models: [
      {
        id: "glm-5.2",
        pricing: {
          inputPerMillion: 1.4,
          outputPerMillion: 4.4,
        },
      },
      {
        id: "glm-5",
        pricing: {
          inputPerMillion: 0.55,
          outputPerMillion: 2.25,
        },
      },
      {
        id: "glm-5.1",
        pricing: {
          inputPerMillion: 0.85,
          outputPerMillion: 3.4,
        },
      },
      {
        id: "glm-4-plus",
        pricing: {
          inputPerMillion: 0.7,
          outputPerMillion: 0.7,
        },
      },
    ],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "GLM_API_KEY",
      modelsUrl: "https://open.bigmodel.cn/api/paas/v4/models",
      authHeader: "bearer",
    },
  },
  dashscope: {
    schemaVersion: 1,
    order: 90,
    type: "dashscope",
    displayName: "DashScope (Qwen)",
    displayNameZh: "通义千问 DashScope",
    aliases: ["dashscope", "qwen"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode",
      anthropicBaseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
    },
    defaultModel: "qwen-max",
    supportedModels: ["qwen-max"],
    models: [
      {
        id: "qwen-max",
        pricing: {
          inputPerMillion: 1.6,
          outputPerMillion: 6.4,
        },
      },
    ],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "DASHSCOPE_API_KEY",
      modelsUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1/models",
      authHeader: "bearer",
    },
  },
  siliconflow: {
    schemaVersion: 1,
    order: 100,
    type: "siliconflow",
    displayName: "SiliconFlow",
    displayNameZh: "硅基流动 SiliconFlow",
    aliases: ["siliconflow"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.siliconflow.cn",
    },
    defaultModel: "deepseek-ai/DeepSeek-V3",
    supportedModels: ["deepseek-ai/DeepSeek-V3"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "SILICONFLOW_API_KEY",
      modelsUrl: "https://api.siliconflow.cn/v1/models",
      authHeader: "bearer",
    },
  },
  volcengine: {
    schemaVersion: 1,
    order: 110,
    type: "volcengine",
    displayName: "Volcengine (Doubao)",
    displayNameZh: "火山引擎（豆包）",
    aliases: ["volcengine", "doubao"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
    },
    defaultModel: "doubao-pro-256k",
    supportedModels: ["doubao-pro-256k"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "VOLCENGINE_API_KEY",
      modelsUrl: "https://ark.cn-beijing.volces.com/api/v3/models",
      authHeader: "bearer",
    },
  },
  baichuan: {
    schemaVersion: 1,
    order: 120,
    type: "baichuan",
    displayName: "Baichuan",
    displayNameZh: "百川",
    aliases: ["baichuan"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.baichuan-ai.com",
    },
    defaultModel: "Baichuan4",
    supportedModels: ["Baichuan4"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "BAICHUAN_API_KEY",
      modelsUrl: "https://api.baichuan-ai.com/v1/models",
      authHeader: "bearer",
    },
  },
  stepfun: {
    schemaVersion: 1,
    order: 130,
    type: "stepfun",
    displayName: "StepFun",
    displayNameZh: "阶跃星辰 StepFun",
    aliases: ["stepfun"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.stepfun.com",
    },
    defaultModel: "step-2-16k",
    supportedModels: ["step-2-16k"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "STEPFUN_API_KEY",
      modelsUrl: "https://api.stepfun.com/v1/models",
      authHeader: "bearer",
    },
  },
  sensenova: {
    schemaVersion: 1,
    order: 135,
    type: "sensenova",
    displayName: "SenseNova",
    displayNameZh: "商汤日日新 SenseNova",
    aliases: ["sensenova"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://token.sensenova.cn",
    },
    defaultModel: "sensenova-6.7-flash-lite",
    supportedModels: ["sensenova-6.7-flash-lite"],
    models: [],
    docs: {
      handlingEn:
        "Drops null strict / response_format / non-function tools, merges system messages",
      handlingZh:
        "清理 strict:null / response_format / 非 function 工具,合并 system 消息",
    },
    sync: {
      envVar: "SENSENOVA_API_KEY",
      modelsUrl: "https://token.sensenova.cn/v1/models",
      authHeader: "bearer",
    },
  },
  yi: {
    schemaVersion: 1,
    order: 140,
    type: "yi",
    displayName: "Yi (01.AI)",
    displayNameZh: "零一万物 Yi",
    aliases: ["yi"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.lingyiwanwu.com",
    },
    defaultModel: "yi-large",
    supportedModels: ["yi-large"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "YI_API_KEY",
      modelsUrl: "https://api.lingyiwanwu.com/v1/models",
      authHeader: "bearer",
    },
  },
  modelscope: {
    schemaVersion: 1,
    order: 145,
    type: "modelscope",
    displayName: "ModelScope",
    displayNameZh: "魔搭 ModelScope",
    aliases: ["modelscope"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api-inference.modelscope.cn",
    },
    defaultModel: "deepseek-ai/DeepSeek-V3",
    supportedModels: ["deepseek-ai/DeepSeek-V3"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "MODELSCOPE_API_KEY",
      modelsUrl: "https://api-inference.modelscope.cn/v1/models",
      authHeader: "bearer",
    },
  },
  xai: {
    schemaVersion: 1,
    order: 150,
    type: "xai",
    displayName: "xAI (Grok)",
    displayNameZh: "xAI（Grok）",
    aliases: ["xai", "grok"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.x.ai",
    },
    defaultModel: "grok-4.3",
    supportedModels: ["grok-4.3", "grok-3-latest"],
    models: [
      {
        id: "grok-4.3",
        pricing: {
          inputPerMillion: 1.25,
          outputPerMillion: 2.5,
        },
      },
      {
        id: "grok-3-latest",
        pricing: {
          inputPerMillion: 3,
          outputPerMillion: 15,
        },
      },
    ],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "XAI_API_KEY",
      modelsUrl: "https://api.x.ai/v1/models",
      authHeader: "bearer",
    },
  },
  mistral: {
    schemaVersion: 1,
    order: 160,
    type: "mistral",
    displayName: "Mistral",
    displayNameZh: "Mistral",
    aliases: ["mistral"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.mistral.ai",
    },
    defaultModel: "mistral-large-latest",
    supportedModels: ["mistral-large-latest"],
    models: [
      {
        id: "mistral-large-latest",
        pricing: {
          inputPerMillion: 2,
          outputPerMillion: 6,
        },
      },
    ],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "MISTRAL_API_KEY",
      modelsUrl: "https://api.mistral.ai/v1/models",
      authHeader: "bearer",
    },
  },
  groq: {
    schemaVersion: 1,
    order: 170,
    type: "groq",
    displayName: "Groq",
    displayNameZh: "Groq",
    aliases: ["groq"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.groq.com/openai",
    },
    defaultModel: "llama-3.3-70b-versatile",
    supportedModels: ["llama-3.3-70b-versatile"],
    models: [
      {
        id: "*",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
    ],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "GROQ_API_KEY",
      modelsUrl: "https://api.groq.com/openai/v1/models",
      authHeader: "bearer",
    },
  },
  together: {
    schemaVersion: 1,
    order: 180,
    type: "together",
    displayName: "Together",
    displayNameZh: "Together",
    aliases: ["together"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.together.xyz",
    },
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    supportedModels: ["meta-llama/Llama-3.3-70B-Instruct-Turbo"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "TOGETHER_API_KEY",
      modelsUrl: "https://api.together.xyz/v1/models",
      authHeader: "bearer",
    },
  },
  fireworks: {
    schemaVersion: 1,
    order: 190,
    type: "fireworks",
    displayName: "Fireworks",
    displayNameZh: "Fireworks",
    aliases: ["fireworks"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.fireworks.ai/inference",
    },
    defaultModel: "accounts/fireworks/models/llama-v3p1-70b-instruct",
    supportedModels: ["accounts/fireworks/models/llama-v3p1-70b-instruct"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "FIREWORKS_API_KEY",
      modelsUrl: "https://api.fireworks.ai/inference/v1/models",
      authHeader: "bearer",
    },
  },
  cerebras: {
    schemaVersion: 1,
    order: 200,
    type: "cerebras",
    displayName: "Cerebras",
    displayNameZh: "Cerebras",
    aliases: ["cerebras"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.cerebras.ai",
    },
    defaultModel: "llama-3.3-70b",
    supportedModels: ["llama-3.3-70b"],
    models: [
      {
        id: "*",
        pricing: {
          inputPerMillion: 0,
          outputPerMillion: 0,
        },
      },
    ],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "CEREBRAS_API_KEY",
      modelsUrl: "https://api.cerebras.ai/v1/models",
      authHeader: "bearer",
    },
  },
  perplexity: {
    schemaVersion: 1,
    order: 210,
    type: "perplexity",
    displayName: "Perplexity",
    displayNameZh: "Perplexity",
    aliases: ["perplexity"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.perplexity.ai",
    },
    defaultModel: "sonar-pro",
    supportedModels: ["sonar-pro"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "PERPLEXITY_API_KEY",
      modelsUrl: "https://api.perplexity.ai/models",
      authHeader: "bearer",
    },
  },
  cohere: {
    schemaVersion: 1,
    order: 220,
    type: "cohere",
    displayName: "Cohere",
    displayNameZh: "Cohere",
    aliases: ["cohere"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.cohere.com/compatibility",
    },
    defaultModel: "command-r-plus",
    supportedModels: ["command-r-plus"],
    models: [],
    docs: {
      handlingEn: "Generic",
      handlingZh: "通用",
    },
    sync: {
      envVar: "COHERE_API_KEY",
      modelsUrl: "https://api.cohere.com/compatibility/v1/models",
      authHeader: "bearer",
    },
  },
  openrouter: {
    schemaVersion: 1,
    order: 230,
    type: "openrouter",
    displayName: "OpenRouter",
    displayNameZh: "OpenRouter",
    aliases: ["openrouter"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://openrouter.ai/api",
    },
    defaultModel: "deepseek/deepseek-v4-flash",
    supportedModels: ["deepseek/deepseek-v4-flash"],
    models: [],
    docs: {
      handlingEn: "None",
      handlingZh: "无",
    },
    sync: {
      envVar: "OPENROUTER_API_KEY",
      modelsUrl: "https://openrouter.ai/api/v1/models",
      authHeader: "bearer",
    },
  },
  orcarouter: {
    schemaVersion: 1,
    order: 235,
    type: "orcarouter",
    displayName: "OrcaRouter",
    displayNameZh: "OrcaRouter",
    aliases: ["orcarouter"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "https://api.orcarouter.ai/v1",
    },
    defaultModel: "orcarouter/auto",
    supportedModels: ["orcarouter/auto"],
    models: [],
    docs: {
      handlingEn: "None",
      handlingZh: "无",
    },
    sync: {
      envVar: "ORCAROUTER_API_KEY",
      modelsUrl: "https://api.orcarouter.ai/v1/models",
      authHeader: "bearer",
    },
  },
  custom_openai_compatible: {
    schemaVersion: 1,
    order: 240,
    type: "custom_openai_compatible",
    displayName: "Custom",
    displayNameZh: "自定义",
    aliases: ["custom_openai_compatible"],
    protocols: ["openai_chat_completions"],
    endpoints: {
      baseUrl: "",
    },
    defaultModel: "",
    supportedModels: [],
    models: [],
    docs: {
      handlingEn: "None (set Base URL yourself)",
      handlingZh: "无（Base URL 用户自己填）",
    },
  },
} as const;

export const GENERATED_PROVIDER_PRESETS = {
  mimo: {
    baseUrl: "https://api.xiaomimimo.com/v1",
    protocols: ["openai_chat_completions", "anthropic_messages"],
    defaultModel: "mimo-v2.5-pro",
    reasoningModel: "mimo-v2.5-pro",
    anthropicBaseUrl: "https://api.xiaomimimo.com/anthropic",
  },
  deepseek: {
    baseUrl: "https://api.deepseek.com",
    protocols: ["openai_chat_completions", "anthropic_messages"],
    defaultModel: "deepseek-flash",
    reasoningModel: "deepseek-v4-pro",
    anthropicBaseUrl: "https://api.deepseek.com/anthropic",
  },
  anthropic: {
    baseUrl: "https://api.anthropic.com",
    protocols: ["anthropic_messages"],
    defaultModel: "claude-opus-4-8",
  },
  copilot: {
    baseUrl: "https://api.githubcopilot.com",
    protocols: ["anthropic_messages", "openai_chat_completions"],
    defaultModel: "claude-sonnet-4.6",
    anthropicBaseUrl: "https://api.githubcopilot.com",
  },
  openai: {
    baseUrl: "https://api.openai.com",
    protocols: ["openai_chat_completions", "openai_responses"],
    defaultModel: "gpt-5.6-terra",
    responsesBaseUrl: "https://api.openai.com",
  },
  google_gemini: {
    baseUrl:
      "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    protocols: ["openai_chat_completions"],
    defaultModel: "gemini-3.5-flash",
  },
  kimi: {
    baseUrl: "https://api.moonshot.cn",
    protocols: ["openai_chat_completions", "anthropic_messages"],
    defaultModel: "kimi-k3",
    reasoningModel: "kimi-k3",
    anthropicBaseUrl: "https://api.moonshot.cn/anthropic",
    extraHeaders: '{"User-Agent":"KimiCLI/1.40.0"}',
  },
  minimax: {
    baseUrl: "https://api.minimax.chat",
    protocols: ["openai_chat_completions"],
    defaultModel: "MiniMax-M1",
  },
  glm: {
    baseUrl: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
    protocols: ["openai_chat_completions"],
    defaultModel: "glm-5.2",
    anthropicBaseUrl: "https://open.bigmodel.cn/api/anthropic",
  },
  dashscope: {
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode",
    protocols: ["openai_chat_completions"],
    defaultModel: "qwen-max",
    anthropicBaseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
  },
  siliconflow: {
    baseUrl: "https://api.siliconflow.cn",
    protocols: ["openai_chat_completions"],
    defaultModel: "deepseek-ai/DeepSeek-V3",
  },
  volcengine: {
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
    protocols: ["openai_chat_completions"],
    defaultModel: "doubao-pro-256k",
  },
  baichuan: {
    baseUrl: "https://api.baichuan-ai.com",
    protocols: ["openai_chat_completions"],
    defaultModel: "Baichuan4",
  },
  stepfun: {
    baseUrl: "https://api.stepfun.com",
    protocols: ["openai_chat_completions"],
    defaultModel: "step-2-16k",
  },
  sensenova: {
    baseUrl: "https://token.sensenova.cn",
    protocols: ["openai_chat_completions"],
    defaultModel: "sensenova-6.7-flash-lite",
  },
  yi: {
    baseUrl: "https://api.lingyiwanwu.com",
    protocols: ["openai_chat_completions"],
    defaultModel: "yi-large",
  },
  modelscope: {
    baseUrl: "https://api-inference.modelscope.cn",
    protocols: ["openai_chat_completions"],
    defaultModel: "deepseek-ai/DeepSeek-V3",
  },
  xai: {
    baseUrl: "https://api.x.ai",
    protocols: ["openai_chat_completions"],
    defaultModel: "grok-4.3",
  },
  mistral: {
    baseUrl: "https://api.mistral.ai",
    protocols: ["openai_chat_completions"],
    defaultModel: "mistral-large-latest",
  },
  groq: {
    baseUrl: "https://api.groq.com/openai",
    protocols: ["openai_chat_completions"],
    defaultModel: "llama-3.3-70b-versatile",
  },
  together: {
    baseUrl: "https://api.together.xyz",
    protocols: ["openai_chat_completions"],
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
  },
  fireworks: {
    baseUrl: "https://api.fireworks.ai/inference",
    protocols: ["openai_chat_completions"],
    defaultModel: "accounts/fireworks/models/llama-v3p1-70b-instruct",
  },
  cerebras: {
    baseUrl: "https://api.cerebras.ai",
    protocols: ["openai_chat_completions"],
    defaultModel: "llama-3.3-70b",
  },
  perplexity: {
    baseUrl: "https://api.perplexity.ai",
    protocols: ["openai_chat_completions"],
    defaultModel: "sonar-pro",
  },
  cohere: {
    baseUrl: "https://api.cohere.com/compatibility",
    protocols: ["openai_chat_completions"],
    defaultModel: "command-r-plus",
  },
  openrouter: {
    baseUrl: "https://openrouter.ai/api",
    protocols: ["openai_chat_completions"],
    defaultModel: "deepseek/deepseek-v4-flash",
  },
  orcarouter: {
    baseUrl: "https://api.orcarouter.ai/v1",
    protocols: ["openai_chat_completions"],
    defaultModel: "orcarouter/auto",
  },
  custom_openai_compatible: {
    baseUrl: "",
    protocols: ["openai_chat_completions"],
    defaultModel: "",
  },
} as const;

export const GENERATED_MIMO_ENDPOINTS = {
  payg: {
    baseUrl: "https://api.xiaomimimo.com/v1",
    anthropicBaseUrl: "https://api.xiaomimimo.com/anthropic",
  },
  tokenPlanRegions: {
    cn: {
      baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
      anthropicBaseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
    },
    sgp: {
      baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
      anthropicBaseUrl: "https://token-plan-sgp.xiaomimimo.com/anthropic",
    },
    ams: {
      baseUrl: "https://token-plan-ams.xiaomimimo.com/v1",
      anthropicBaseUrl: "https://token-plan-ams.xiaomimimo.com/anthropic",
    },
  },
} as const;

export const GENERATED_DEEPSEEK_SUPPORTED_MODELS = [
  "deepseek-flash",
  "deepseek-v4-pro",
] as const;
